[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
build_flags =
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
